lib/ca.py

Note this is against one of your dev branches, not master.
This should not be merged to master yet as I do not think it is python2 compatible, but I needed this working on a beamline with python3 _now_ so here it is.
The source of the rouge 'b' is that the `str` or `repr` of a byte object in python 3 include the 'b' so that the string formatting `'%s%s' % (value, NULLCHAR)` -> `"b'value_str'b'\\x00"'` which is less than fully helpful.
I suspect that I have done an end-run around some of the stuff it `utils`.  Do you mind picking up a dependency on `six` (which I think would greatly simplify `utils`) or should I re-do this using existing functions (and if so, some direction as to which ones would be appreciated).

Fix py3 strings

---

lib/ca.py

this removes the Severity Check on attach_context(), which is apparently needed on Darwin.

remove severity check from attach_context() (needed on Darwin?)

---

epics/ca.py

We don't use the regular "linux-" prefix, but instead different depending on operating system. E.g. SL6, centos7 and so on. Therefore we depend on that you actually use EPICS_HOST_ARCH.

Search for libca.so in EPICS_HOST_ARCH also.

---

epics/pv.py

The `get_pv` function accepts the `form` parameter but was not using it when creating new PVs. This meant `Device.add_pv` was unable to create PVs with `form='ctrl'` for example. This pull request fixes this by passing in the `form` parameter when instantiating a new PV.

Make get_pv respect the form argument when creating new PVs

---

epics/ca.py

- ascii_string correctly handles `''` and does not need to be
short-cirucited
- if the length of the input is 0, then the length is re-set to the
maximum length of the array.  Later, there is a check that if ftype ==
dbr.CHAR then add 1 to count.  This results in a error from trying to
put a too-long array to the PV.
There are still bugs in handling the edge cases of very long
strings (the null char might not get written).

FIX: fix two bugs handling empty strings

---

epics/ca.py
tests/ca_unittest.py
tests/pv_unittest.py

* Fixes waveform of strings `put()` in Python 3, added a unit test for it. It was just a missing a call to `ascii_string`. 
* Adds a context manager to pause simulator updating for the tests. I found that if one test failed it might affect the others, as simulator updating was never resumed
* All tests are passing now in 2.7/3.4 (minus the 'real motor' one which I don't have an IOC for - I added a skiptest for this in my other PR #49).

Fix: Py3k waveform of strings put()

---

epics/ca.py

Addresses bug in #51, as pointed out by @mccullerip.

specify args for attach_context, avoid threading segfaults

---

epics/ca.py

FIX: Always return the PV alarm status in the pv.status attribute

---

epics/ca.py

@newville Would you be open to this change? Downstream, we'd like to display 3 decimal places by default when precision is not defined by EPICS. But pyepics currently doesn't provide enough information for us to know whether precision is undefined or actually 0.
cc @dchabot You and I [had the same thought](https://github.com/NSLS-II/ophyd/pull/284#issuecomment-191796313).

API: If precision is not given, return None, not 0.

---

epics/pv.py

When the PV class goes to generate the `char_value` for a char waveform it checks whether the value is a numpy `ndarray` and if so converts it to a list. This check was producing an `AttributeError` if numpy was not installed and thus failing to set `char_value`. This change makes `_set_charval` first check if numpy is available before doing the`isinstance` check.

Fix bug in PV._set_charval when numpy is not installed

---

.travis.yml
tests/pv_unittest.py
tests/pvnames.py

This adds preliminary continuous integration testing via a docker image that runs an EPICS IOC with a simulated area detector, simulated motors, and the pyepics testioc records.
That docker image is currently external, but it should probably be brought into the pyepics organization: 
* [github repo](https://github.com/klauer/simioc-docker/tree/pyepics-docker) (where the Dockerfile is located that generates the docker image)
* [docker hub](https://hub.docker.com/r/klauer/simioc-docker/) (where the docker image is stored)
Here's what a passing build looks like: https://travis-ci.org/klauer/pyepics/builds/121256923
~~TODO: change the currently-skipped tests which reference real motors to use simulated motors~~

Add travis configuration for CI testing

---

.travis.yml
epics/ca.py
epics/pv.py

I ~~think~~ hope this will finally resolve the crashes we've seen both locally and on travis.
This PR adds:
* atexit cleanup: `clear_channel` called on all PVs in the cache
* checks to make sure `PV.disconnect` doesn't call `clear_subscription` after the atexit code is called
* automatic gdb backtrace shown if py.test still segfaults (see 3.4 or 3.5 [here](https://travis-ci.org/klauer/pyepics/jobs/124517278) for an example)
Side-note: we need some multi-context tests to consider them supported

FIX: python 3 atexit cleanup

---

.travis.yml
epics/ca.py
epics/multiproc.py
tests/test_pool.py
tests/test_threading.py

* Adds some basic context creation and `CAThread` tests
* Cleaned up `CAPool` tests for multiprocessing - they are now run automatically in py.test
* Confirmed that darwin check is now unnecessary in `CAThread`
Working on OSX locally, and passing on travis.
Closes #37 (not directly, but because the tests are passing on OSX)
Closes #15 (multiprocessing tests now work fine with the same code on OSX/Linux)

FIX/CLN: context-related tweaks and basic threading tests

---

doc/ca.rst
doc/pv.rst
epics/ca.py
epics/pv.py

this addresses #70 and adds PV properties of `seconds` and `nanoseconds`, both of which are integers taken directly from the EPICS DBR timestamp.   The `nanosecond` property will give higher precision timing for PV events.

Highprecision timestamps

---

.travis.yml

This will make it possible to start more than one docker instance
and have them live side-by-side.
This binds each servers 5064 tcp port to a random port in the range
7000-8000 which is sorted out by libca as part of the search process.
The udp multi-cast passes through on 5064 (as it did before).
We do not need to expose the heart-beat outside of the docker manager.

CI: tweak how docker is started

---

epics/ca.py
epics/dbr.py

In follow up to http://www.aps.anl.gov/epics/tech-talk/2017/msg00797.php . . .
With this patch (based on work by @FreddieAkeroyd), pyepics is now working with IronPython (32-bit only). Tested on Windows 7 with IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (32-bit)
using ca and Com dlls included with the pyepics distribution. 
Patched from tag 3.2.6.

Iron python testing

---

epics/ca.py
epics/pv.py
epics/utils3.py
tests/ca_type_conversion.py
tests/pv_type_conversion.py
tests/pv_unittest.py

Bug in ca.put() when working with waveforms of strings.
Old code is problematic since "cout" parameter is defined with "len(value)". In case of strings or bytes len() returns number of characters, but pypepics expects number of elements. When ftype == dbr.STRING, one string is one element, therefore count=1.
This results in following behaviour:
1) ca.put('abc')
- py2 .. instead of ['abc'], waveform will be ['a', 'b', 'c']
- py3 .. type error ... since value[i] is of type int if value is of type bytes
2) In second case when value is a list with a single element -->  ca.put(['abc'g), pyepics will try to handle it as a single value and will try to assign a list() to the object which expects strings(py2)/bytes(py3) ---> Type error.
This commit handles strings/bytes properly.

Fix puting single value to waveform of strings.

---

epics/ca.py
epics/dbr.py

this is a small change for Python2 + Windows64 to add padding to the access_rights_handler structure.  It now works on Py2+Win64, and the change here should not affect any other platforms or parts of the code.

fix access rights structure for Py2 and Win64

---

epics/ca.py

This may resolve the Travis test failures with NOLIBCA. 
First,  pre-loading of libCom happens only on Windows, where it is necessary, but not on Linux, where it is not necessary, and where it was causing problems with the NOLIBCA option. 
Second, _find_lib() really looks at PYEPICS_LIBCA, but not for PYEPICS_LIBCOM even when looking for 'Com'.  If this envvar is set  but we're really looking for 'Com', it will look for libCom next to libca.
This does work for me on Windows 64bit.

need to preload libCom on Windows

---

doc/overview.rst
epics/__init__.py
epics/ca.py
tests/pv_unittest.py

This PR improves the epics.caget_many method to accept the same arguments as epics.caget, adds documentation for epics.caget_many, and adds a feature to epics.caget where if you pass it a list or tuple of PV names, it will call epics.caget_many.
A (very basic) unit test for epics.caget_many has been added as well.

Improve batch-getting PVs.

---

setup.py

Addresses #110 by installing all libraries in `epics.clibs` for all supported architectures, unless `NOLIBCA` is defined. In that case, no libs are installed.

BUG: install all the libs

---

epics/ca.py
epics/motor.py
tests/pv_unittest.py

This PR changes `ca.create_channel` to remove the `poll()` if a connection callback is defined (as is usual).  On Windows64, this call was definitely slow -- taking ~15 ms -- which is not seen on Linux or OSX. 
I'm not sure why that poll is necessary.  That is, it still doesn't ensure that the connection callback has been run before `create_channel` returns.  
FWIW, there is also a change to add more things to the initial list of motor attributes, which is how I started looking into this problem in the first place.   
Travis seems to say this is passing, which is pleasantly surprising -- I half expected a failure when testing connection callbacks.
I'm not sure this needs to be merged immediately.  But, any objections or concerns?

Nopoll on ca create conncb

---

epics/ca.py

this addresses #117, adding `posixseconds` and `nanoseconds` elements to the dict returned by `ca.get_timevars()`.

add posixseconds/nanoseconds to output of get_timevars()

---

epics/ca.py

This tries to address #120, allowing `ca.create_subscription()` on unconnected PVs.
This probably needs documentation and maybe a test or two.  I'm posting this now mostly to demonstrate that this is possible, and might be useful.....

allow ca.create_subscription() on unconnected channels

---

doc/ca.rst
doc/pv.rst
epics/ca.py
epics/pv.py
tests/pv_unittest.py
tests/test_pool.py

Goal
----
* Update `epics.PV` metadata when `PV.get()` is called. 
* Allow access to metadata and value from a specific get request through `PV.get_with_metadata()`, where a kwarg can indicate a request for different DBR types: `ctrl`, `time`, or `None` (default to PV.form)
API additions were needed to make this possible, but it should all be backward-compatible. The original `epics.ca.get` and `epics.ca.get_complete` just now call the 'metadata-rich' versions `epics.ca.get_with_metadata` and `epics.ca.get_complete_with_metadata`.
Metadata update example
-------------
If `pv.form` is set to 'time', then timestamp, status, severity will all be updated before returning. This means that `pv.timestamp` now accurately reflects the timestamp just received from the get request.
Similarly, if …

ENH: on PV.get(), update all CTRL/STS/TIME metadata

---

epics/pv.py

This uses NELM>1 to decide if a PV is an array, not `count > 1`.  
This is useful for array PVs that may sometimes contain only one element. 
See, for example, https://github.com/APS-USAXS/ipython-usaxs/issues/102

use nelm to determine if a PV is an array, not count: allows 1-element arrays

---

epics/ca.py
tests/Setup/simulator.py
tests/ca_unittest.py

This allows `ca.get()` and related `ca.get***` to run with an unconnected channel ID and return `None` for an unconnected channel,  and not simply raise an exception in the decorator.  
This should address #141

allow get to return  (as documented) for unconnected Channels

---

epics/ca.py

Current master manually wraps functions, but there is a utility available in the standard library to do this for you. Verified it's available in 2.7 and up:
https://docs.python.org/2/library/functools.html#functools.wraps

REF: use functools.wraps

---

epics/ca.py
epics/pv.py
tests/pv_unittest.py

Adds a test `pv_unittest.test_multithreaded_put_complete` which fails on master since put_completes are keyed solely on pvname (irrespective of context or anything else). There is no guarantee that the callback received corresponds to any specific user request.
This issue could be potentially seen in single-threaded cases, but the included test is done with many threads to provide some degree of certainty that it's doing what is expected.
My notes from the other PR this was separated from:
> For the put-with-callback, the exact response of the IOC is not our (library) concern. It's important to split up the client and server's role in this case. The logic is something like the following for a single request: "client request A was made. Did request A finish according to the IOC?" The …

REF: Add and fix test pv_unittest.test_multithreaded_put_complete

---

epics/ca.py
epics/dbr.py
epics/pv.py
tests/pv_unittest.py
tests/test_threading.py

This is the largest change from #147 that couldn't be easily separated. It's also the part that deserves the most scrutiny prior to (potential) merging.
Issues
-------
1. Multiple threads attempting to read the same PV quickly fail due to a race condition with the built-in `epics.ca._cache`
2. `ca.get()` which returns anything but `ECA_NORMAL` will show up in pyepics as `TimeoutError`
3. `get_timevars`, `get_ctrlvars` duplicate a lot of `get_with_metadata` code unnecessarily.
4. Access rights, connection callbacks were being run for all contexts
This did not make sense to me, and it is not present in this refactor. If I misunderstood that, we should revisit this. (@dchabot, I believe this was from your PR?)
5. `_namecache` is not keyed on context. This PR removes the namecache entirely. …

REF: rework CA cache for get requests (improved thread safety and such)

---

epics/ca.py
epics/pv.py
tests/pv_unittest.py

In the case of timeout, these functions return `None`. Comparing against `None` is necessary prior to attempting to update internal PV state dictionaries.
Also adds a test based on #68. It *appears* to no longer be an issue, but I'm not 100% certain as of yet. More tests should be done.

FIX: timeout during get_timevars

---

epics/pv.py
tests/pv_unittest.py

Allows any thread, using any CA context, to access an `epics.PV` object safely.
The modified test verifies the functionality alongside `epics.CAThread`, which is largely made unnecessary with this change.
A much simpler example of which this PR aims to fix, which will fail on master (click for details):
<details>
```python
import threading
import epics
def test(i):
print()
print('---- test {} ----'.format(i))
epics.ca.create_context()
print('created context', epics.ca.current_context())
print(pv.get())
print(pv.nelm)
print(epics.ca._cache)
pv = epics.PV('Py:ao1', auto_monitor=False)
pv.wait_for_connection()
for i in range(5):
thread = threading.Thread(target=test, args=(i, ))
thread.start()
thread.join()
```
With the current master, we see:
```sh
$ python threaded_access.py
---- test 0 …
```

ENH: add _ensure_context decorator, guard against multithreaded access of `epics.PV`

---

epics/ca.py
epics/pv.py

A more complicated but more flexible alternative to #154:
* Allows `auto_monitor` to be changed before connection or while connected.
* If set prior to connection, the behavior will be as it is in the current master (checking the count if `None`, etc.)
* If set after connection, the `auto_monitor` is re-evaluated as follows:
* If newly disabled via `auto_monitor = False` and a monitor exists, then the subscription will be cleared
* If enabled via `auto_monitor = True` and a monitor does not exist, a monitor will be created
* If maybe-enabled via `auto_monitor = None` and a monitor does not exist, a monitor will be created
* If a mask is reconfigured via `auto_monitor = DBE_LOG|DBE_ALARM`, the current monitor will be replaced (or created)

REF: allow changing of PV.auto_monitor at any time

---

epics/pv.py

With this PR, both `PV.clear_auto_monitor` and `PV.reconnect` will not reset the boolean `auto_monitor` - which determines whether or not to set up a monitor automatically on PV connection. 
This means that the one-time logic that set `auto_monitor` upon the initial connection will be re-used for subsequent reconnections (except if the user modifies the attribute directly).
Closes #145

FIX: auto monitor on reconnect

---

epics/ca.py
epics/pv.py
tests/pv_unittest.py
tests/test_cas.py
tests/test_multiprocessing.py
tests/test_threading.py

The overall goal of this PR is to fix `clear_channel` not clearing the cache appropriately. This meant that subsequent calls to `create_channel` after `clear_channel` could return a stale `chid` and cause a segfault. 
Fixing the above uncovered an atexit cleanup bug (with `finalize_libca`) where channels could potentially get cleared twice, causing a segfault.
I believe this PR now addresses both of the above. Additional changes and details are as follows:
* Also adds a simple repr for further debugging of cache-related things.
* Removed the `_get_or_create_*` methods after thinking more about how `create_channel` operates 
- This simplifies things considerably, and almost everything goes through `get_cache` now.
* Add a `channel id` cache (`epics.ca._chid_cache`).
- `chid` is effectively …

FIX: clear channel should remove cache item

---

epics/ca.py

Grab the entry again from the cache. Between the time the lock was attempted and acquired, the cache may have changed.
Follow-up to the never-ending #161

FIX: re-check context_cache after sentinel lock

---

epics/ca.py

Closes #171
libca apparently(erroneously) leaks UDP sockets when calling `poll` in a connection callback thread. More details and debugging information in #171.

FIX: replace connection callback poll() with sleep()

---

epics/device.py

The __dir__() method of epics.Device() was concatenating dictionary keys and lists. This is fine under python2, but broke in later versions of python3. Convert the dict_keys iterables to lists to fix the problem transparently for py2 and py3. Maybe there is a better solution for this, but the quick fix in this pull request seems to solve the problem for now.
This solution has not yet been tested on all versions!
I have not checked whether similar problems would potentially arrise in other modules.

Fix problem with listing attributes in python3 in __dir__() method

---

.travis.yml
epics/autosave/save_restore.py

This is a fix for Tech-Talk https://epics.anl.gov/tech-talk/2019/msg01425.php, and following the recommendations in that discussion for what a valid PV name should be.  
As it turns out, pyepics does essentially no enforcement or expectation of what a valid PV name is except in the sense of "accepted by `ca_create_channel()`", except in the `autosave` module where files of PV names are parsed.

fix `pv_name` definition supported by autosave

---

epics/motor.py

This adds explicit `get()` and `put()` methods to `epics.Motor` to better support aliases, addressing #181 . With this change, one can now do
>>> import epics
>>> motor = epics.Motor('motorname')
>>> print(motor.get('drive'). motor.get('base_speed'))
and
>>> motor.put('base_speed', 2.0)

add explicit get()/put() methods to Motor that allow use of aliases

---

epics/alarm.py
epics/pv.py
epics/wx/motorpanel.py
epics/wx/utils.py
epics/wx/wxlib.py

This adds two small fixes for maintenance, should give no change in functionality:
a) replace `hasattr(obj, '__call__')` with `callable(obj)`.  I forget which early version of Python 3 required the uglier form, but `callable` has been supported for many versions now.
b) use modern forms of "get function name" and "get filename of function" so that these can be reported with `PV.info`.

Misc updates

---

epics/ca.py
epics/dbr.py

This changes the ctypes structure definition for `access_rights_handler_args` to explicitly unpack the read/write access bit fields.
An attempt to fix #189

explicitly unpack access bits, as required for Py3.7.6

---

epics/__init__.py

This PR makes `epics.caget_many()` much faster in instances where some of the PVs don't connect.  Instead of using `ca.connect_channel()` (which will connect to each channel serially, with a separate timeout for each), I've changed it to create all the channels, then loop over all of them, repeatedly checking connection status.  If all PVs aren't connected after a new `conn_timeout` parameter, they are skipped when getting values.
Previously, `caget_many()` would wait for up to `len(pvlist)*timeout`, which could be minutes if there were many disconnected PVs.  Now, it is possible to give up on those disconnected PVs much quicker.
While writing this PR I found that the implementation is really similar to something @brunoseivam mentions in #141.

Use a single connection timeout for all PVs in caget_many.

---

epics/pv.py

Description
Mixing Issue (from email) and fix: 
import epics
p = epics.PV('EnumTypePV')
p.char_value
will return something like '0' or '1' instead of the enum name, say, 'Infected' or 'VirusFree'.  Of course, doing
p.get(as_string=True)
will return the proper string representation, and then `p.char_value` will be correct.
This PR fixes that by forcing the `char_value` property to call `PV._set_charval()`.

fix PV.char_value to return proper string without needing PV.get(as_string=True)

---

epics/pv.py

This PR is a continuation of the work started by @klauer at https://github.com/pyepics/pyepics/pull/203.
The tests were failing because `_check_auto_monitor` was never being called after `self.connected` was set. Moving it after that makes the tests pass locally and also fixes the tests hanging at Typhos.
🤞 that they will pass at Travis here as well.

FIX: Do not block if disconnected when changing auto_monitor settings - continued

---

epics/ca.py

This PR builds on @klauer's suggested fix for an issue that began in https://github.com/bluesky/ophyd/issues/834 and resurfaced in https://github.com/bluesky/ophyd/pull/866. This also affected several downstream projects, which began seeing unexpected exceptions in their test suites.
The issue occurs when Python is shutting down. Since the order in which Python tears everything down is not very consistent or controllable, libca is sometimes finalized before downstream code has a chance to run its cleanup. When that cleanup later invokes pyepics functionality that requires libca, exceptions are thrown. Some of them cannot be caught.
An example of this can be triggered by running the following snippet against the current master:
```python
import epics
class Broken:
def __init__(self, pv): …
```

Prevent exceptions after libca is finalized during teardown

---

.gitignore
.travis.yml
epics/ca.py
epics/dbr.py
tests/README
tests/test_dbr.py

**Problem**
When a get callback receives a type it does not recognize, it will raise TypeError due to invalid use of type. It is caused by a fallback type instance which not an integer as the rest of the code expects.
**Solution**
1) This update fails casting if the type is not recognized because it is not able to tell much about the supplied memory pointer. In case of `_onGetEvent`, this will yield an error. In case of `_onMonitorEvent` this will end the function silently similar to other cases here.
2) This update adds a unit test which covers the behavior `bdr.cast_args`. This unit test is included into the tests in `.travis.yml`.
3) This update adds `venv` and by-products of vscode and `pip install -e .` into `.gitignore'.
**Test**
1) `test_bdr` was run manually.
2) Updated pyepics …

PycSimpleType appearing in the function native_type

---

.github/workflows/test-with-conda.yml
epics/pv.py
tests/test_pv_disconnect.py

This PR is a proposal to fix the issue #156 .
The issue occured because the disconnect method left some references to the PV object dangling, which prevented the garbage collector to collect the PV object.
The method behaves otherwise the same as before, i.e. the connection is still cached by epics.ca and reused if a new PV object is created for the same signal.
I also included a set of tests to verify the interaction of the disconnect method with other methods provided by the library.

FIX memory leak on PV.disconnect() #156

---

epics/pv.py

This follows the idea in #221 to remove all references to callbacks on `PV.disconnect()`.
See #221, #220, #156

remove all callbackes for PV on discaonnect (see GH #221)

---

setup.py

setuptools' pkg_resources is used in the ca module, but setuptools was not
listed as a dependency, yet.
Add setuptools as a dependency, because pkg_resources is used in epics/ca.py.
This tries to fix issue #224 
Though setuptools is installed most of the time, [pkg_resources does not ship with Python](https://www.python.org/dev/peps/pep-0365/) itself and hence shouldn't been taken for granted.

Add setuptools as runtime requirement

---

MANIFEST.in

Recursively exclude .pyc caching files from being included in source distributions in order to prevent issues with further build tools (like stdeb) or different setups trying to use the cache file though it might not match the current environment.
We were facing the problem that [stdeb](https://github.com/astraw/stdeb) cannot cope with .pyc files being part of the sdist tar.gz.
The newest release on PyPI (https://pypi.org/project/pyepics/#files 3.5.1 https://files.pythonhosted.org/packages/6c/cd/f97b676b6903e6f88bfced3817964559c20a1e3c6cd5244fa188f76fff75/pyepics-3.5.1.tar.gz) includes a `scripts/__pycache__/mpanel.cpython-37.pyc` file, thus causing the issue with stdeb.
As the pyc files are already excluded from the main directory, I guess it is intended, that these files are not part of …

Exclude pyc files recursively

---

.github/workflows/test-with-conda.yml

Closes #249
Enable workflow execution on pull request (open, synchronization, reopen). This makes results of the test visible even for pull-requests from a forked repository. Without this, the results are visible only at the forked repository.

Added pull-request to the list of events which trigger a workflow

---

.gitignore
epics/ca.py
epics/pv.py
tests/test_ca_clearcache.py

Closes #247 
This update prevents a random crash (SIGSEGV) after using ca.clear_cache. This crash is caused by calling ca_clear_subscription (done in pv.PV.disconnect when a monitor is used) any time after ca_clear_channel (done in ca.clear_cache) on the same channel. The randomness is caused by CG because pv.PV.disconnect is called from pv.PV.__del__. This update resolves the problem by disconnecting all PVs found in the PV cache prior clearing all channels.

Prevented unsubscribing events from a cleared channel

---

epics/devices/srs570.py

We are missing a comma in the `attrs` tuple resulting into an implicit string concatenation.

Device/SRS570: fix attrs bug

---

epics/alarm.py

Currently printing an `Alarm` object does not work since its `__repr__` references `pv.name` instead of `pv.pvname`.

Alarm.__repr__ references pv.name instead of pv.pvname

---

.github/workflows/test-python38.yml
tests/Setup/start_ioc.sh

This fixes the GitHub Actions workflow scripts to specify the Python version correctly for testing.   
The key change is to use mamba consistently to install Anaconda packages. 
This PR illustrates that the master branch fails with Python 3.8 as noted in #266 and proposed to be fixed in #267.

fixes to gh actions workflow, using mamba and CONDA_PREFIX to specify Python version

---

epics/ca.py
setup.cfg

- Adds a dependency on `importlib_resources` if python version is 3.8
- Imports `files` from there if it is not available from `importlib.resources`
Fixes #266

(#266) On Py3.8, install and import importlib_resources instead of importlib.resources

---

epics/wx/wxlib.py

As title. There was a typo in the wx epics widgets PVMixin that prevented the background color from being set.

Fixes an issue where background color of wx epics widgets with the PMixin couldn't be set

---

epics/autosave/save_restore.py
epics/motor.py

This has two fixes. The first is a straightforward fix that fixes an issue with the motor position not being set correctly for a Motor device when using set_position. This was occurring for the Slit pseudomotor in the Optics synApps package, but might occur for other pseudomotors.
The second is a probably not great fix for an issue where the first time I try to restore values to a set of PVs, it often seems to give a not connected error for one or two of them (out of the ~70 that are being restored), something like: Cannot connect to "18ID_DMC_E03:18.DIR". I've done a bit of debugging, and this seems to just be a timing issue. if I add a 0.1 s sleep after trying to connect, the PVs always (well, within my limited testing) read as connected. I'm assuming it has something to do with how the …

Autosave fix

---

epics/__init__.py
epics/pv.py

This work-in-progress PR adds a `monitor_delta` argument to `PV`, `get_pv`, and `camonitor` to set a threshold value for "monitor events".    This applies only to scalar float/double PVs.  
Many records will have an MDEL field that can be set independently for this purpose (reducing events from being sent by value).   
The decision of whether to send an event is by absolute value of the change in a value:
``` 
reportable_event = abs(current_value - last_value) > monitor_delta
```
with this change, the PV class will:  
1. try to set the corresponding MDEL field.  If this works, it limits events being sent from the IOC/server to all subscribers. 
2. if that does not work (for example, the client does not have write permission), then monitor_delta is simulated in the internal PV callback …

Monitor delta
