pyepics/pyepics

epics/ca.py

units attribute needs BYTE2STR()

---

epics/ca.py
epics/utils.py
epics/utils2.py
epics/utils3.py

Fix py3 strings

---

epics/ca.py
epics/pv.py
tests/pv_unittest.py

A second and much more focused attempt at fixing #53. Does not require simulator or test IOC changes.
I'll be addressing comments from the last PR inline with the code shortly.

Fix "emptyish" char waveforms

---

epics/wx/motorpanel.py
epics/wx/utils.py
epics/wx/wxlib.py

this makes changes to the wx modules necessary to work with both Phoenix or classic wxPython

fixes for wx.Phoenix

---

epics/devices/scan.py

adds many methods to the scan device for working with the Epics Scan record

Device fixes: adds more features to scan device

---

epics/__init__.py
epics/pv.py

fixes for connection timeouts, especially so that unconnected PVs timeout in the specified time.

Timeout fixes

---

epics/ca.py
epics/pv.py
tests/pv_unittest.py

allow restriction of counts in callback of waveforms

---

.travis.yml
doc/ca.rst
doc/pv.rst
epics/ca.py
epics/dbr.py
epics/pv.py
tests/test_cas.py

ENH: access rights event handling

---

epics/devices/mca.py

this is a small, contained fix to the MCA device.  Should cause no problems

add sum property to mca device

---

.travis.yml
INSTALL
doc/installation.rst
epics/ca.py
setup.py

Fix libca install optout

---

epics/ca.py
epics/pv.py
epics/utils.py

Addresses #89.
Perhaps not so much a fix as a blindfold...

MNT: do attempt disconnect if libca is None

---

INSTALL
README.md
README.rst

Make installation instructions slightly more prominent.
Changes formatting from restructured text to markdown.
Addresses #93.

DOC: update readme

---

doc/arrays.rst
doc/autosave.rst
doc/ca.rst
doc/devices.rst
doc/installation.rst
doc/overview.rst
doc/pv.rst

update docs fo 3.3.0, addresses #93

Doc for 330

---

epics/autosave/save_restore.py

Otherwise PVs with this char trig a parserException

add char '-'

---

doc/advanced.rst
doc/installation.rst
doc/overview.rst

this updates the docs for `caget_many()` and friends, and re-writes the "connecting to many PVs" section of the advanced topics chapter.

update docs for caget_many() and discussion of getting many PV values

---

epics/wx/motordetailframe.py
epics/wx/motorpanel.py
epics/wx/ogllib.py
epics/wx/utils.py
epics/wx/wxlib.py
scripts/Motor_Display.py
scripts/mpanel.py

this fixes a number of small Python 3 / wxPython 4 problems for code in the wx/ folder.  I'm not sure it fixes *all* problems, but at least 1 wxPython4 + pyepics app now works for me.

Py3 / wxPython4 fixes

---

epics/pv.py

Address issue #124.
attn @hhslepicka

BUG: set default subscription mask to VALUE|ALARM

---

epics/pv.py

ENH: respect formatting iff as_string is True

---

epics/__init__.py
epics/pv.py

Deal with timeouts the same way in caget, caput and camonitor

---

epics/pv.py

Still related to #129, I missed this bit that also had to be changed. Now everything seems to work as expected.

Fix wait_for_connection timeout

---

epics/ca.py

Addresses issue #142.
Attn: @brunoseivam

FIX: race condition

---

epics/ca.py

MNT: remove undefined raise_on_unconnected

---

epics/pv.py

FIX: have get_pv respect callbacks

---

epics/device.py
epics/motor.py

pass  from Device/Motor.get() to PV.get() 

---

epics/__init__.py

This is a slight cleanup of #200, partly addressing #141, and should give better timing accuracy.  
I tested with 10000 PVs, 95 of which are not connected and the rest scalar values on a single subnet.
Using `conn_timeout=1.0` (now the default), I see the runtime drop from about 2.4 seconds (current master, after #200) to about 1.6 seconds (this PR), while also consistently getting exactly 95 `None` values.

caget_many(): cleanups (and maybe speed ups, and better timing accuracy)

---

epics/pv.py

FIX: Clean access and connection callbacks at clear_callbacks.

---

tests/Setup/start_ioc.sh

Enable testing with darwin using screen

---

scripts/mpanel.py

https://wiki.debian.org/Python3-six-removal

remove one leftover six usage

---

epics/_version.py
epics/autosave/save_restore.py
epics/device.py
epics/devices/mca.py
epics/devices/struck.py
epics/wx/motordetailframe.py
tests/UnsortedTests/autosave_test.py
tests/UnsortedTests/ca_fastconn.py
tests/UnsortedTests/memleak.py
tests/UnsortedTests/memleak_put.py
tests/UnsortedTests/memory_motor.py
tests/test_aodevice.py
tests/test_ca_unittests.py

This is an initial attempt to fix #242. A few points to note:
1. I'm new to this repository (hello everyone! 👋). My familiarity with both code and its underlying concepts (including epics itself), is still developing.
2. I didn't find a way to successfully run the tests locally
3. While this commit does not resolve several other file handling bugs (for instance, files are not explicitly closed in some cases), I plan to address these in separate PRs.

Fix text encoding

---

epics/ca.py
tests/Setup/simulator.py
tests/test_pv_unittests.py

Str waveforms 1 elem

---

doc/ca.rst
epics/ca.py

disable CA messages by default, allow enabling before CA is initialzed.

Disable ca messages

---

epics/autosave/save_restore.py

Fixes issues where autosave:
- Wouldn't restore values if the pv had no value in the save file
- Wouldn't load .req files with macro definitions (e.g. P=)
- Wouldn't propagate macro definitions to a .req file loaded within another file
For the last item, suppose you have first.req which has the line:
file "second.req", P=IOC1
and second.req has the line:
file "third.req", P=$(P)
The value of P (IOC1) from first.req wouldn't propagate into third.req.

Fixes autosave issues
